# Use root/example as user/password credentials
version: '3.1'

services:

  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: amdaripassword
      MYSQL_DATABASE: amdaridb
      MYSQL_USER: amdariuser
      MYSQL_PASSWORD: amdariuserpassword
    volumes:
      - mysqldb-volume:/var/lib/mysql
    ports:
      - "3306:3306"

  postgresdb:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    #shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: amdariuserpassword
      POSTGRES_USER: amdariuser
      POSTGRES_DB: amdaridb
    volumes:
      - postgresdb-volume:/var/lib/postgresql/data
    ports:
      - 5435:5432 

  sqlserverdb:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Amdaripassword_01"

    ports:
      - 1433:1433
    
    volumes:
      - sqlserverdb-volume:/var/opt/mysql


volumes:
  mysqldb-volume: {}
  postgresdb-volume: {}
  sqlserverdb-volume: {}
